projekt/apka/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
    path('comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('generate-image/', views.generate_image, name='generate_image'),
    path('get_title/', views.get_title, name='get_title'),
    path('get_hashtags/', views.get_hashtags, name='get_hashtags'),
]

projekt/projekt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apka/', include('apka.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projekt/apka/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser

class Hashtag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=300)
    content = models.TextField()
    image = models.ImageField(upload_to='posts/', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    hashtags = models.ManyToManyField(Hashtag, related_name='posts')

    def __str__(self):
        return self.title

    @property
    def likes_count(self):
        return Like.objects.filter(post=self).count()
    
    def is_liked_by_user(self, user):
        return Like.objects.filter(post=self, user=user).exists()
    
    def get_hashtags(self):
        return self.hashtags.all()
    
    @staticmethod
    def search_by_hashtag(query):
        if query:
            return Post.objects.filter(hashtags__name__icontains=query)
        else:
            return Post.objects.all()

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_likes')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f"{self.user} likes {self.post}"

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} commented on {self.post.title}"

class CustomUser(AbstractUser):
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='custom_user_set',
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='custom_user_set',
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )

projekt/apka/forms.py
# forms.py
from django import forms
from .models import Post, User, Comment
from django.contrib.auth.forms import UserCreationForm

class PostForm(forms.ModelForm):
    hashtags = forms.CharField(max_length=200, required=False, help_text='Enter hashtags separated by commas')
    
    class Meta:
        model = Post
        fields = ['title', 'content', 'image', 'hashtags']

class SignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'password1', 'password2')
        widgets = {
            'password1': forms.PasswordInput(attrs={'placeholder': 'Password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 2, 'placeholder': 'Add a comment...'}),
        }

projekt/apka/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Like, Hashtag, Comment
from .forms import PostForm, CommentForm
from django.http import JsonResponse
import os
from replicate.client import Client
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm
import requests
from django.contrib.auth.decorators import login_required
import uuid
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize, sent_tokenize 
import nltk
from collections import Counter
import spacy

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/apka')
        else:
            return render(request, 'apka/login.html', {'error': 'Invalid username or password'})
    return render(request, 'apka/login.html')

def logout_view(request):
    logout(request)
    return redirect('login')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'apka/login.html')
    else:
        form = SignUpForm()
    return render(request, 'apka/signup.html', {'form': form})

def index(request):
    if 'sessionid' not in request.COOKIES:
        return redirect('logout')
    
    user = request.user
    generated_image_url = request.session.pop('generated_image_url', None)

    if request.method == 'GET':
        query = request.GET.get('q')
        if query:
            posts = Post.search_by_hashtag(query).order_by('-created_at')
        else:
            posts = Post.objects.all().order_by('-created_at')
        return render(request, 'apka/index.html', {'posts': posts})
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            if generated_image_url:
                post.image = generated_image_url
            post.save()
            
            hashtags_input = form.cleaned_data.get('hashtags')
            if hashtags_input:
                hashtags_list = [tag.strip() for tag in hashtags_input.split(',')]
                for tag in hashtags_list:
                    hashtag, created = Hashtag.objects.get_or_create(name=tag)
                    post.hashtags.add(hashtag)
            
            return redirect('index')
    else:
        form = PostForm()

    posts = Post.objects.all().order_by('-created_at')

    context = {
        'user': user,
        'posts': posts,
        'form': form
    }
    return render(request, 'apka/index.html', context)

@login_required
def like_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    like, created = Like.objects.get_or_create(user=request.user, post=post)
    if not created:
        like.delete()
    return redirect('index')

@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('/apka')
    else:
        form = CommentForm()
    return render(request, 'your_template.html', {'form': form})

@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    if request.user == comment.user:
        comment.delete()
        return redirect('/apka')
    else:
        return JsonResponse({'status': 'error'}, status=403)

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        post.delete()
        return redirect('/apka')
    return JsonResponse({'status': 'error'}, status=403)

def generate_image(request):
    if request.method == 'POST':
        prompt = request.POST.get('prompt')
        client = Client(api_token=os.environ.get('REPLICATE_API_TOKEN'))
        input = {
            "prompt": prompt,
            "scheduler": "K_EULER"
        }
        output = client.run(
            "stability-ai/stable-diffusion:ac732df83cea7fff18b8472768c88ad041fa750ff7682a21affe81863cbe77e4",
            input=input
        )
        
        image_url = output[0]
        image_response = requests.get(image_url)
        image_uuid = str(uuid.uuid4())
        image_extension = os.path.splitext(image_url)[1]
        
        image_name = f"{image_uuid}{image_extension}"

        image_path = os.path.join(settings.MEDIA_ROOT, image_name)
        with open(image_path, 'wb') as f:
            f.write(image_response.content)
        
        relative_image_path = os.path.join(image_name)
        request.session['generated_image_url'] = relative_image_path
        
        return JsonResponse({'image_url': image_url})
    else:
        return JsonResponse({'error': 'Method not allowed'}, status=405)

def get_hashtags(request):
    if request.method == 'POST':
        text = request.POST.get('content', '')
        print(text)
        nlp = spacy.load("en_core_web_sm")
        doc = nlp(text)    
        nouns = [token.text for token in doc if token.pos_ == "NOUN"]
        adjectives = [token.text for token in doc if token.pos_ == "ADJ"]
        noun_counts = Counter(nouns)
        adjective_counts = Counter(adjectives)
        top_nouns = noun_counts.most_common(4)
        top_adjectives = adjective_counts.most_common(4)
        hashtags = [noun[0] for noun in top_nouns] + [adj[0] for adj in top_adjectives]
        print(hashtags)
        return JsonResponse({'hashtags': hashtags})
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)

def get_title(request):
    if request.method == 'POST':
        text = request.POST.get('content', '')
        nltk.download('punkt')
        stopWords = set(stopwords.words("english")) 
        words = word_tokenize(text)
        
        # Creating a frequency table to keep the  score of each word    
        freqTable = dict() 
        for word in words: 
            word = word.lower() 
            if word in stopWords: 
                continue
            if word in freqTable: 
                freqTable[word] += 1
            else: 
                freqTable[word] = 1

        # Creating a dictionary to keep the score of each sentence 
        sentences = sent_tokenize(text) 
        sentenceValue = dict() 
        
        for sentence in sentences: 
            for word, freq in freqTable.items(): 
                if word in sentence.lower(): 
                    if sentence in sentenceValue: 
                        sentenceValue[sentence] += freq
                    else: 
                        sentenceValue[sentence] = freq 
        
        sumValues = 0
        for sentence in sentenceValue: 
            sumValues += sentenceValue[sentence] 
        
        # Highest value sentence will be the summary. 
        summary = max(sentenceValue, key=sentenceValue.get)
        return JsonResponse({'title': summary})
    else:
        return JsonResponse({'error': 'Invalid request method'}, status=400)

projekt/apka/templates/apka/index.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Social Media Site</title>
    <link rel="stylesheet" type="text/css" href="{% static 'apka/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="navbar">
        <h1>SocialAI</h1>
        <a class="right" href="{% url 'logout' %}">
            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-logout" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#b969a8" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />
                <path d="M9 12h12l-3 -3" />
                <path d="M18 15l3 -3" />
            </svg>
        </a>
    </div>
    <div class="main">
        <div class="container create_post" id="create_post_container">
            Create post
            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input class="form_title" type="text" id="id_title" name="title" placeholder="Title">
                <button type="button" onclick="generateTitle()">Generate Title</button>
                <textarea class="form_content" id="id_content" name="content" rows="2" placeholder="Content"></textarea>
                <textarea class="form_content" id="id_hashtags" name="hashtags" rows="1" placeholder="Hashtags"></textarea>
                <button type="button" onclick="generateHashtags()">Generate Hashtags</button>
                <label for="id_image" class="form_image">
                    Upload image
                    <input type="file" id="id_image" name="image" accept="image/*" style="display: none;">
                </label>
                <span>or</span>
                <textarea class="form_content" id="textInput" placeholder="Enter prompt"></textarea>
                <button type="button" onclick="generateImage()">Generate Image</button>
                <input type="hidden" id="generated_image_url" name="generated_image_url">
                <img id="preview-img" src="#" style="display: none;">
                <button class="form_button" type="submit">Post</button>
            </form>
        </div>
        <div class="posts">
            <div class="container">
                <form action="" method="GET">
                    <input type="text" name="q" placeholder="Search by hashtag">
                    <button type="submit">Search</button>
                </form>
            </div>
            {% for post in posts %}
                <div class="container">
                    <div class="post">
                        <div>
                            <span class="author">
                                <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-user" width="32" height="32" viewBox="0 0 24 24" stroke-width="1.5" stroke="#b969a8" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                    <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                    <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0" />
                                    <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />
                                </svg>
                                {{ post.author }}
                            </span>
                        </div>
                        <div class="post_content">
                            <span class="title">{{ post.title }}</span>
                            <span class="content">{{ post.content }}</span>
                            {% if post.image %}
                            <img id="post_image" src="{{ post.image.url }}" alt="Post Image">
                            {% endif %}
                            <span class="content">{{ post.likes_count }} likes | {{ post.created_at }}</span>
                            <span class="hashtag">
                                {% for hashtag in post.get_hashtags %}
                                    #{{ hashtag.name }}
                                {% endfor %}
                            </span>
                            <div class="comments">
                                <h3>Comments ({{ post.comments.count }})</h3>
                                <hr>
                                {% for comment in post.comments.all %}
                                    <div class="post">
                                        <span class="author">{{ comment.user }}</span>
                                        <div class="post_content">
                                            {% if comment.user == user %}
                                                <div class="right">
                                                    <form method="POST" action="{% url 'delete_comment' comment.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="delete_button">
                                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                                                <path d="M4 7l16 0" />
                                                                <path d="M10 11l0 6" />
                                                                <path d="M14 11l0 6" />
                                                                <path d="M5 7l1 12a2 2 0 0 0 2 2l8 0a2 2 0 0 0 2 -2l1 -12" />
                                                                <path d="M9 7l1 -3h4l1 3" />
                                                            </svg>
                                                        </button>
                                                    </form>
                                                </div>
                                            {% endif %}
                                            <span class="content">{{ comment.content }}</span>
                                            <span class="content">{{ comment.created_at }}</span>
                                        </div>
                                    </div>
                                {% endfor %}
                                <hr>
                                <form method="POST" action="{% url 'add_comment' post.id %}">
                                    {% csrf_token %}
                                    <textarea name="content" rows="2" placeholder="Add a comment..."></textarea>
                                    <button type="submit">Comment</button>
                                </form>
                            </div>
                        </div>
                        {% if post.author == user %}
                            <div class="right">
                                <form method="POST" action="{% url 'delete_post' post.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="delete_button">
                                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#2c3e50" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                            <path d="M4 7l16 0" />
                                            <path d="M10 11l0 6" />
                                            <path d="M14 11l0 6" />
                                            <path d="M5 7l1 12a2 2 0 0 0 2 2l8 0a2 2 0 0 0 2 -2l1 -12" />
                                            <path d="M9 7l1 -3h4l1 3" />
                                        </svg>
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                        {% if post.author != user %}
                            <div class="right">
                                <form action="{% url 'like_post' post.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit">
                                        {% if post|is_liked_by_user:user %}
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart-broken" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#781716" fill="#ff2825" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                                <path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                                                <path d="M12 6l-2 4l4 3l-2 4v3" />
                                            </svg>
                                        {% else %}
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-heart" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#781716" fill="#ff2825" stroke-linecap="round" stroke-linejoin="round">
                                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                                <path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" />
                                            </svg>
                                        {% endif %}
                                    </button>
                                </form>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>        
    </div>
</body>
</html>

<script>
    $(document).ready(function() {
        $('#id_image').change(function() {
            const file = this.files[0];
            const imgPreview = document.getElementById('preview-img');
            if (file) {
                const reader = new FileReader();
                reader.onload = function(event) {
                    imgPreview.src = event.target.result;
                    imgPreview.style.display = 'block';
                }
                $('#create_post_container').css('height', '750px');
                reader.readAsDataURL(file);
            } else {
                $('#create_post_container').css('height', '450px');
                imgPreview.style.display = 'none';
            }
        });

        function generateImage() {
            var prompt = $('#textInput').val();
            var csrftoken = $('[name=csrfmiddlewaretoken]').val();
            $.ajax({
                url: "{% url 'generate_image' %}",
                type: "POST",
                data: {
                    'prompt': prompt,
                    'csrfmiddlewaretoken': csrftoken,
                },
                success: function(response) {
                    var imageUrl = response.image_url;
                    $('#preview-img').attr('src', imageUrl);
                    $('#preview-img').css('display', 'block');
                    $('#generated_image_url').val(response.image_url);
                    $('#create_post_container').css('height', '750px');
                }
            });
        }
        window.generateImage = generateImage;

        function generateTitle() {
            var content = $('#id_content').val();
            var csrftoken = $('[name=csrfmiddlewaretoken]').val();
            console.log(content)
            $.ajax({
                url: "{% url 'get_title' %}",
                type: "POST",
                data: {
                    'content': content,
                    'csrfmiddlewaretoken': csrftoken,
                },
                success: function(response) {
                    console.log(response)
                    var title = response.title;
                    $('#id_title').val(title);
                    $('#generated_title_hashtags').html('Generated Title: ' + title);
                }
            });
        }
        window.generateTitle = generateTitle;

        function generateHashtags() {
            var content = $('#id_content').val();
            var csrftoken = $('[name=csrfmiddlewaretoken]').val();
            $.ajax({
                url: "{% url 'get_hashtags' %}",
                type: "POST",
                data: {
                    'content': content,
                    'csrfmiddlewaretoken': csrftoken,
                },
                success: function(response) {
                    console.log(response)
                    var hashtags = response.hashtags.join(', ');
                    $('#id_hashtags').val(hashtags);
                    $('#generated_title_hashtags').html('Generated Hashtags: ' + hashtags);
                }
            });
        }
        window.generateHashtags = generateHashtags;
    });
</script>

projekt/apka/templates/apka/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log in</title>
    <link rel="stylesheet" type="text/css" href="{% static 'apka/login.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <div class="main">
        <h1>Log in to apka!</h1>
        <form class="login" method="post">
            {% csrf_token %}
            {{ error }}
            <input type="text" name="username" placeholder="Username"><br>
            <input type="password" name="password" placeholder="Password"><br>
            <input class="button" type="submit" value="Login">
        </form>
        <h3>Or go to sign up <a href="{% url 'signup' %}">here</a></h3>
    </div>
</body>

projekt/apka/templates/apka/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'apka/login.css' %}">
    <title>Sign Up</title>
</head>
<body>
    <div class="main">
        <h1>Sign Up to apka!</h1>
        <form class="login" method="post">
            {% csrf_token %}
            <div>
                {{ form.username.label_tag }}
                {{ form.username }}
                {% if form.username.errors %}
                    <div class="error">{{ form.username.errors }}</div>
                {% endif %}
            </div>
            <div>
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                {% if form.password1.errors %}
                    <div class="error">{{ form.password1.errors }}</div>
                {% endif %}
            </div>
            <div>
                {{ form.password2.label_tag }}
                {{ form.password2 }}
                {% if form.password2.errors %}
                    <div class="error">{{ form.password2.errors }}</div>
                {% endif %}
            </div>
            <button type="submit">Sign Up</button>
        </form>
        <h3>Or go to log in <a href="{% url 'login' %}">here</a></h3>
    </div>    
</body>
</html>